### PR TITLE
Only pass items to npm that are needed

### PR DESCRIPTION
**Pull request by knownasilya**
See https://github.com/ember-cli/ember-cli/issues/6147 for context

### CODE REVIEW

**Comment by Turbo87** [comment]
@knownasilya in the last round of cleanup we determined that we would like to use the `files` key in `package.json` instead of `.npmignore` files. could you update the PR?

**Comment by knownasilya** [comment]
Would it be just the index.js, or do I need to add the folders as well to the files array?

**Comment by Turbo87** [comment]
we will need the `index.js` and the `lib` folder. I am unsure about the `preprocessors.js` file, but I'd say include it too.

**Comment by Turbo87** [comment]
LGTM, thanks!

@rwjblue r?

**Pull request merged**
